services:
  hr-interview-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: hr-interview-api:test
    container_name: hr-interview-api
    restart: always
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: test
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
