server:
  port: 8080

spring:
  application:
    name: hr-interview-api
  profiles:
    active: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto

knife4j:
  enable: true

logging:
  file:
    path: logs
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
      total-size-cap: 10GB
